### PR TITLE
Modernize Gradle

### PR DESCRIPTION
**Pull request by cdietrich**
See #776

### CODE REVIEW

**Comment by cdietrich** [comment]
TODO: what about ide task

**Comment by jonahgraham** [comment]
I'm looking at this now. I think this is fine and we'll leave the bnd upgrade to 7.0 (with its Java 17 requirement) for another day.

**Comment by cdietrich** [comment]
ok i have rebase rebased and squashed. lets see what build says

**Comment by cdietrich** [comment]
@jonahgraham ok to merge before the release?

**Comment by jonahgraham** [comment]
> @jonahgraham ok to merge before the release?

I will review the generated poms/jars to make sure no unexpected changes and I will merge when/if I approve soon.

**Comment by cdietrich** [comment]
opk. cause i need to drop off soon

**Review by jonahgraham — APPROVED** [review]

**Pull request merged**
