### PR TITLE
Update DAP protocol up to 1.65

### PR DESCRIPTION
**Pull request by Soarex16**

### CODE REVIEW

**Comment by Soarex16** [comment]
@jonahgraham I combined all updates into one PR.

**Comment by jonahgraham** [comment]
Thanks - all in one PR, but with one commit per DAP version is very helpful and should make it easier for me to review.

@KamasamaK can you have a look too - is this still in your wheelhouse?

**Review by jonahgraham — CHANGES_REQUESTED** [review]
A quick look at this looks good, I want a second set of eyes to compare the implementation here to the spec. 

Some housekeeping needs to be done before this can be merged.

The SCHEMA_VERSION in the protocol/services files needs updating, such as https://github.com/eclipse-lsp4j/lsp4j/blob/51711e19fd675df1cee260146bdb8ff644f521a7/org.eclipse.lsp4j.debug/src/main/java/org/eclipse/lsp4j/debug/DebugProtocol.xtend#L31

And the supported version in the README needs updating:

https://github.com/eclipse-lsp4j/lsp4j/blob/51711e19fd675df1cee260146bdb8ff644f521a7/README.md?plain=1#L63

And an entry in the changelog is needed - single line, like https://github.com/eclipse-lsp4j/lsp4j/blob/51711e19fd675df1cee260146bdb8ff644f521a7/CHANGELOG.md?plain=1#L61

**Comment by Soarex16** [comment]
I updated the schema version, but didn't touch other things because I don't want to interfere with the release processes.

**Review by jonahgraham — APPROVED** [review]
Thanks @Soarex16 - This LGTM, but I did make a few small changes. Can you confirm  that I didn't mess anything up.

What I changed:

- Added `Since` comment on new fields/classes
- Add "paperwork" for changelog/readme/schema version in the java code
- Added `memoryReference` to `SetExpressionResponse` 
- Changed some wording to match what is in the upstream spec

**Comment by Soarex16** [comment]
@jonahgraham yes, I missed `memoryReference` in `SetExpressionResponse`. I checked the changelog again and everything should be fine now.

Thank you!

**Comment by jonahgraham** [comment]
Thank you @Soarex16 for the contribution.

I have merged and kicked off the [build](https://ci.eclipse.org/lsp4j/job/lsp4j-multi-build/job/main/). It should end up in snapshots in a little while.

If you want a released version, please comment on #807 any constraints/timelines you have.

**Comment by KamasamaK** [comment]
I've finally been able to review this and found a few minor issues and one big issue that I'll address in another PR.

**Pull request merged**
